### ISSUE TITLE
`debian-repo-tool` is unable to copy some recent Ubuntu repositories

### ISSUE THREAD

**Issue by clepple** [indygreg/linux-packaging-rs#10]
(using `main`, which is currently commit a00f146de2cc0fbce5e8076725ecc4e1fe5dee56 - just two commits after `debian-packaging/0.16.0`. Shouldn't be platform-specific, but most of my testing was with cargo/rustc 1.71.0 on an Ubuntu focal x86_64 host.)

While trying to mirror the Ubuntu focal distribution to local media, I ran across what appears to be a difference in how Debian and Ubuntu structure their trees of `Contents` files. The result is that `debian-repo-tool` panics part of the way through the Ubuntu copy. The same panic happens with Ubuntu jammy.

The full backtrace is a little messy (and currently lost in the scrollback), but by printing out some of the fields, I think it is because the Ubuntu archive has a single `Contents-<arch>` file at the root of the dist, and Debian has several `<component>/Contents-<arch>` files. This throws off the release file parsing, and the code tries to start the slice at -1 in `impl<'a> TryFrom<ReleaseFileEntry<'a>> for ContentsFileEntry<'a>`:

https://github.com/indygreg/linux-packaging-rs/blob/a00f146de2cc0fbce5e8076725ecc4e1fe5dee56/debian-packaging/src/repository/release.rs#L354

I'm attaching a YAML file that reproduces the error, though I admit that it is not the most efficient (I think it ends up copying 2GB before panicking). Open to suggestions on how you think a smaller unit test should look (e.g. throw in the whole Release file for Ubuntu, or just an excerpt inline).

The patch is also not my finest work (still working through the early chapters of The Rust Book), but I got a little lost tracking down whether the rest of the code really handles `component == ""` (which is I guess how you might label the Ubuntu `Contents-<arch>` file), so it just returns `DebianError::ReleaseIndicesEntryWrongType` if there is no component directory prefix. From what I can tell, applying that patch allows me to make a mostly-functional copy of the Ubuntu jammy repository.

- [mirror-ubuntu-focal-partial.yaml.txt](https://github.com/indygreg/linux-packaging-rs/files/12256330/mirror-ubuntu-focal-partial.yaml.txt)
- [linux-packaging-rs.handle-contents-outside-component.patch](https://github.com/indygreg/linux-packaging-rs/files/12256333/linux-packaging-rs.handle-contents-outside-component.patch)

Thanks for open-sourcing this code!

**Comment by indygreg** [comment]
Thanks for reporting this.

It looks like modern Ubuntu is publishing the top-level `Contents-*` files in their Release files. Not sure what caused this change. But it did break our assertion in the Release parsing code that all `Contents-*` files are in sub-directories.

I'll work on a patch plus test coverage of this scenario.
